#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║           GUÍA PARA VERIFICAR PRECARGA DE DATOS EN AWS                       ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 PASO 1: VERIFICAR LOGS DE CONTENEDORES EN AWS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔍 Para ECS (Elastic Container Service):"
echo "   1. Ve a la consola de AWS → ECS"
echo "   2. Selecciona tu cluster"
echo "   3. Selecciona el servicio (cliente-service o catalog-service)"
echo "   4. Ve a la pestaña 'Logs' o 'CloudWatch Logs'"
echo "   5. Busca líneas como:"
echo "      • ✅ INICIALIZACIÓN COMPLETADA EXITOSAMENTE"
echo "      • ✅ Clientes: X registros"
echo "      • ✅ Vendedores: X registros"
echo "      • ✅ Productos: X registros"
echo ""
echo "📱 Comando AWS CLI para ver logs:"
echo "   # Cliente Service"
echo "   aws logs tail /ecs/cliente-service --follow"
echo ""
echo "   # Catalog Service"
echo "   aws logs tail /ecs/catalog-service --follow"
echo ""
echo ""
echo "📋 PASO 2: VERIFICAR DATOS VÍA API"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Reemplaza <URL_AWS> con tu URL de AWS (ALB o API Gateway):"
echo ""
echo "# 1. Verificar Vendedores (3 con UUID hardcodeado)"
echo "curl https://<URL_AWS>/api/v1/vendedores/ | jq '.items | length'"
echo ""
echo "# 2. Verificar Clientes (6 con UUID hardcodeado)"
echo "curl https://<URL_AWS>/api/v1/client/ | jq 'length'"
echo ""
echo "# 3. Verificar Productos (20 productos precargados)"
echo "curl https://<URL_AWS>/api/v1/catalog/items | jq '.items | length'"
echo ""
echo "# 4. Verificar vendedor específico (Carlos Mendoza)"
echo "curl https://<URL_AWS>/api/v1/vendedores/11111111-1111-1111-1111-111111111111"
echo ""
echo "# 5. Verificar clientes de un vendedor"
echo "curl https://<URL_AWS>/api/v1/client/?vendedor_id=11111111-1111-1111-1111-111111111111"
echo ""
echo ""
echo "📋 PASO 3: CONECTARSE DIRECTAMENTE A LA BASE DE DATOS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🗄️ Conectar a RDS de Cliente Service:"
echo "   psql -h <RDS_ENDPOINT> -U cliente_user -d cliente_db"
echo ""
echo "   Luego ejecuta:"
echo "   SELECT COUNT(*) FROM vendedor;  -- Debe retornar 5 (3 hardcoded + 2 extras)"
echo "   SELECT COUNT(*) FROM cliente;   -- Debe retornar 6+ (6 hardcoded + creados)"
echo "   SELECT id, nombre_completo FROM vendedor WHERE id::text LIKE '11111111%';"
echo ""
echo "🗄️ Conectar a RDS de Catalog Service:"
echo "   psql -h <RDS_ENDPOINT> -U catalogo_user -d catalogo_db"
echo ""
echo "   Luego ejecuta:"
echo "   SELECT COUNT(*) FROM producto;   -- Debe retornar 20+"
echo "   SELECT COUNT(*) FROM inventario;  -- Debe retornar inventarios"
echo "   SELECT id, nombre FROM producto LIMIT 5;"
echo ""
echo ""
echo "📋 PASO 4: SI LOS DATOS NO SE CARGARON AUTOMÁTICAMENTE"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔧 Opción A: Reiniciar el servicio en ECS"
echo "   aws ecs update-service --cluster <CLUSTER> --service cliente-service --force-new-deployment"
echo "   aws ecs update-service --cluster <CLUSTER> --service catalog-service --force-new-deployment"
echo ""
echo "🔧 Opción B: Ejecutar manualmente desde un contenedor temporal"
echo "   # Obtener el endpoint de RDS"
echo "   export DATABASE_URL='postgresql+asyncpg://usuario:password@rds-endpoint:5432/database'"
echo ""
echo "   # Cliente Service"
echo "   docker run -it --rm \\"
echo "     -e DATABASE_URL=\"\$DATABASE_URL\" \\"
echo "     <ECR_REGISTRY>/cliente-service:latest \\"
echo "     python3 -m app.populate_db"
echo ""
echo "   # Catalog Service"
echo "   docker run -it --rm \\"
echo "     -e DATABASE_URL=\"\$DATABASE_URL\" \\"
echo "     <ECR_REGISTRY>/catalog-service:latest \\"
echo "     python3 -m app.db_init"
echo ""
echo ""
echo "📋 PASO 5: VARIABLES DE ENTORNO CRÍTICAS EN AWS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Verifica que estas variables estén configuradas en ECS Task Definition:"
echo ""
echo "✅ cliente-service:"
echo "   DATABASE_URL=postgresql+asyncpg://cliente_user:<PASSWORD>@<RDS_ENDPOINT>:5432/cliente_db"
echo ""
echo "✅ catalog-service:"
echo "   DATABASE_URL=postgresql+asyncpg://catalogo_user:<PASSWORD>@<RDS_ENDPOINT>:5432/catalogo_db"
echo ""
echo "⚠️  IMPORTANTE: La contraseña NO debe tener caracteres especiales sin escapar"
echo "   Si tiene caracteres especiales, usa URL encoding: @ = %40, # = %23, etc."
echo ""
echo ""
echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║                     ✅ DATOS QUE SE DEBEN PRECARGAR                          ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 VENDEDORES (3 con UUID hardcodeado):"
echo "   • Carlos Mendoza (11111111-1111-1111-1111-111111111111)"
echo "   • María Fernández (22222222-2222-2222-2222-222222222222)"
echo "   • Andrés Ramírez (33333333-3333-3333-3333-333333333333)"
echo ""
echo "🎯 CLIENTES (6 con UUID hardcodeado y vendedor asignado):"
echo "   • 2 clientes para Carlos Mendoza"
echo "   • 2 clientes para María Fernández"
echo "   • 2 clientes para Andrés Ramírez"
echo ""
echo "🎯 PRODUCTOS (20 con UUID hardcodeado):"
echo "   • Amoxicilina (11111111-1111-1111-1111-000000000001)"
echo "   • Ibuprofeno (11111111-1111-1111-1111-000000000002)"
echo "   • ... (18 productos más)"
echo ""
echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║        🎉 SIGUE ESTOS PASOS PARA VERIFICAR LA PRECARGA EN AWS               ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"

